name: SpawnPerms
main: com.example.spawnperms.SpawnPerms
version: 2.0.0
api-version: 1.20

commands:
  spawnperms:
    description: Manage spawn permissions
  spawnradius:
    description: Change spawn protection radius
  spawnpvp:
    description: Toggle spawn PvP